# Generated by Django 2.2.7 on 2019-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='algo',
            field=models.CharField(default='sha256', max_length=32),
        ),
    ]
